FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY postcss.config.cjs ./
COPY tailwind.config.js ./
COPY vite.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.node.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]