FROM python:3.11-slim
RUN apt-get update && apt-get install -y ffmpeg
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

#EXPOSE 8000

# Add the backend directory to PYTHONPATH
ENV PYTHONPATH=/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]